/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ItemsUuidRouteImport } from './routes/items.$uuid'
import { Route as MapUuidRouteImport } from './routes/map.$uuid'
import { Route as OrbitUuidRouteImport } from './routes/orbit.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsUuidRoute = ItemsUuidRouteImport.update({
  id: '/items/$uuid',
  path: '/items/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const MapUuidRoute = MapUuidRouteImport.update({
  id: '/map/$uuid',
  path: '/map/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitUuidRoute = OrbitUuidRouteImport.update({
  id: '/orbit/$uuid',
  path: '/orbit/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/import': typeof ImportRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/map/$uuid': typeof MapUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/import': typeof ImportRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/map/$uuid': typeof MapUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/import': typeof ImportRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/map/$uuid': typeof MapUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/import'
    | '/items/$uuid'
    | '/map/$uuid'
    | '/orbit/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/import'
    | '/items/$uuid'
    | '/map/$uuid'
    | '/orbit/$uuid'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/import'
    | '/items/$uuid'
    | '/map/$uuid'
    | '/orbit/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  ImportRoute: typeof ImportRoute
  ItemsUuidRoute: typeof ItemsUuidRoute
  MapUuidRoute: typeof MapUuidRoute
  OrbitUuidRoute: typeof OrbitUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$uuid': {
      id: '/items/$uuid'
      path: '/items/$uuid'
      fullPath: '/items/$uuid'
      preLoaderRoute: typeof ItemsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$uuid': {
      id: '/map/$uuid'
      path: '/map/$uuid'
      fullPath: '/map/$uuid'
      preLoaderRoute: typeof MapUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit/$uuid': {
      id: '/orbit/$uuid'
      path: '/orbit/$uuid'
      fullPath: '/orbit/$uuid'
      preLoaderRoute: typeof OrbitUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  ImportRoute: ImportRoute,
  ItemsUuidRoute: ItemsUuidRoute,
  MapUuidRoute: MapUuidRoute,
  OrbitUuidRoute: OrbitUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
