/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ItemsUuidRouteImport } from './routes/items.$uuid'
import { Route as MapUuidRouteImport } from './routes/map.$uuid'
import { Route as ModerationIndexRouteImport } from './routes/moderation.index'
import { Route as OrbitUuidRouteImport } from './routes/orbit.$uuid'
import { Route as OrganisationsIndexRouteImport } from './routes/organisations.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as OrganisationsCorporationsCorporationIdRouteImport } from './routes/organisations.corporations.$corporationId'
import { Route as OrganisationsPoliticsEntityIdRouteImport } from './routes/organisations.politics.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsUuidRoute = ItemsUuidRouteImport.update({
  id: '/items/$uuid',
  path: '/items/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const MapUuidRoute = MapUuidRouteImport.update({
  id: '/map/$uuid',
  path: '/map/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationIndexRoute = ModerationIndexRouteImport.update({
  id: '/moderation/',
  path: '/moderation/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitUuidRoute = OrbitUuidRouteImport.update({
  id: '/orbit/$uuid',
  path: '/orbit/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsIndexRoute = OrganisationsIndexRouteImport.update({
  id: '/organisations/',
  path: '/organisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsCorporationsCorporationIdRoute =
  OrganisationsCorporationsCorporationIdRouteImport.update({
    id: '/organisations/corporations/$corporationId',
    path: '/organisations/corporations/$corporationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganisationsPoliticsEntityIdRoute =
  OrganisationsPoliticsEntityIdRouteImport.update({
    id: '/organisations/politics/$entityId',
    path: '/organisations/politics/$entityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/import': typeof ImportRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/map/$uuid': typeof MapUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/moderation/': typeof ModerationIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/organisations/corporations/$corporationId': typeof OrganisationsCorporationsCorporationIdRoute
  '/organisations/politics/$entityId': typeof OrganisationsPoliticsEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/import': typeof ImportRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/map/$uuid': typeof MapUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/moderation': typeof ModerationIndexRoute
  '/organisations': typeof OrganisationsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/organisations/corporations/$corporationId': typeof OrganisationsCorporationsCorporationIdRoute
  '/organisations/politics/$entityId': typeof OrganisationsPoliticsEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/import': typeof ImportRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/map/$uuid': typeof MapUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/moderation/': typeof ModerationIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/organisations/corporations/$corporationId': typeof OrganisationsCorporationsCorporationIdRoute
  '/organisations/politics/$entityId': typeof OrganisationsPoliticsEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/import'
    | '/items/$uuid'
    | '/map/$uuid'
    | '/orbit/$uuid'
    | '/players/$playerId'
    | '/moderation/'
    | '/organisations/'
    | '/players/'
    | '/organisations/corporations/$corporationId'
    | '/organisations/politics/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/import'
    | '/items/$uuid'
    | '/map/$uuid'
    | '/orbit/$uuid'
    | '/players/$playerId'
    | '/moderation'
    | '/organisations'
    | '/players'
    | '/organisations/corporations/$corporationId'
    | '/organisations/politics/$entityId'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/import'
    | '/items/$uuid'
    | '/map/$uuid'
    | '/orbit/$uuid'
    | '/players/$playerId'
    | '/moderation/'
    | '/organisations/'
    | '/players/'
    | '/organisations/corporations/$corporationId'
    | '/organisations/politics/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  ImportRoute: typeof ImportRoute
  ItemsUuidRoute: typeof ItemsUuidRoute
  MapUuidRoute: typeof MapUuidRoute
  OrbitUuidRoute: typeof OrbitUuidRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  ModerationIndexRoute: typeof ModerationIndexRoute
  OrganisationsIndexRoute: typeof OrganisationsIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  OrganisationsCorporationsCorporationIdRoute: typeof OrganisationsCorporationsCorporationIdRoute
  OrganisationsPoliticsEntityIdRoute: typeof OrganisationsPoliticsEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$uuid': {
      id: '/items/$uuid'
      path: '/items/$uuid'
      fullPath: '/items/$uuid'
      preLoaderRoute: typeof ItemsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$uuid': {
      id: '/map/$uuid'
      path: '/map/$uuid'
      fullPath: '/map/$uuid'
      preLoaderRoute: typeof MapUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation/': {
      id: '/moderation/'
      path: '/moderation'
      fullPath: '/moderation/'
      preLoaderRoute: typeof ModerationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit/$uuid': {
      id: '/orbit/$uuid'
      path: '/orbit/$uuid'
      fullPath: '/orbit/$uuid'
      preLoaderRoute: typeof OrbitUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/': {
      id: '/organisations/'
      path: '/organisations'
      fullPath: '/organisations/'
      preLoaderRoute: typeof OrganisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/corporations/$corporationId': {
      id: '/organisations/corporations/$corporationId'
      path: '/organisations/corporations/$corporationId'
      fullPath: '/organisations/corporations/$corporationId'
      preLoaderRoute: typeof OrganisationsCorporationsCorporationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/politics/$entityId': {
      id: '/organisations/politics/$entityId'
      path: '/organisations/politics/$entityId'
      fullPath: '/organisations/politics/$entityId'
      preLoaderRoute: typeof OrganisationsPoliticsEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  ImportRoute: ImportRoute,
  ItemsUuidRoute: ItemsUuidRoute,
  MapUuidRoute: MapUuidRoute,
  OrbitUuidRoute: OrbitUuidRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  ModerationIndexRoute: ModerationIndexRoute,
  OrganisationsIndexRoute: OrganisationsIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  OrganisationsCorporationsCorporationIdRoute:
    OrganisationsCorporationsCorporationIdRoute,
  OrganisationsPoliticsEntityIdRoute: OrganisationsPoliticsEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
