/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ItemsUuidRouteImport } from './routes/items.$uuid'
import { Route as OrbitUuidRouteImport } from './routes/orbit.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsUuidRoute = ItemsUuidRouteImport.update({
  id: '/items/$uuid',
  path: '/items/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitUuidRoute = OrbitUuidRouteImport.update({
  id: '/orbit/$uuid',
  path: '/orbit/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/items/$uuid': typeof ItemsUuidRoute
  '/orbit/$uuid': typeof OrbitUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explorer' | '/items/$uuid' | '/orbit/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explorer' | '/items/$uuid' | '/orbit/$uuid'
  id: '__root__' | '/' | '/explorer' | '/items/$uuid' | '/orbit/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRoute
  ItemsUuidRoute: typeof ItemsUuidRoute
  OrbitUuidRoute: typeof OrbitUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$uuid': {
      id: '/items/$uuid'
      path: '/items/$uuid'
      fullPath: '/items/$uuid'
      preLoaderRoute: typeof ItemsUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit/$uuid': {
      id: '/orbit/$uuid'
      path: '/orbit/$uuid'
      fullPath: '/orbit/$uuid'
      preLoaderRoute: typeof OrbitUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRoute,
  ItemsUuidRoute: ItemsUuidRoute,
  OrbitUuidRoute: OrbitUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
